### PR TITLE
Replace PyYAML with ruamel.yaml

### PR DESCRIPTION
**Pull request by micahellison**
This PR changes our YAML config parser from PyYAML to ruamel.yaml as a first step toward being able to support and preserve comments in the config file (#946) and refactor the config data retrieval (#1102).

The only behavioral change I've found so far is that when there are duplicate keys at the same level in the config file, PyYAML picks the first key, while ruamel.yaml picks the last key. I filed #1415 to address this.

### Checklist

- [x] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [x] I have included a link to the relevant issue number.
- [x] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [x] I have written new tests for these changes, as needed.

### CODE REVIEW

**Comment by wren** [comment]
The format for the config file changes a bit with this. It's still valid YAML, but it's a different style. Is that what we want?
Before:
```yaml
colors:
    body: none
    date: black
    tags: yellow
    title: cyan
```

After:
```yaml
colors: {body: none, date: black, tags: yellow, title: cyan}
```

**Comment by micahellison** [comment]
Got the collapsing YAML issue fixed with the by setting the YAML object's default_flow_style to false.

**Review by wren — DISMISSED** [review]
Looks good as soon as conflicts are resolved. 🤠

**Review by wren — APPROVED** [review]
🤠

**Pull request merged**
