### PR TITLE
Add added option to _print_edited_summary

### LINKED ISSUE #1198: Wrong delete count when manually changing entries
### Environment
```
> jrnl --diagnostic
jrnl: v2.7
Python: 3.9.2 (default, Feb 19 2021, 17:43:04)
[Clang 12.0.0 (clang-1200.0.32.29)]
OS: Darwin 20.3.0
```

  - Install method: homebrew

### Current Behavior
When editing a list of entries in my editor, and adding one entry in the list, after saving the file, the summary says that a negative number of entries was deleted. 

```
> jrnl -n 5 --edit
[-1 entries deleted, 1 entry modified]
```

### Expected Behavior
I would expect to see the following output when adding one entry and changing another:
```
> jrnl -n 5 --edit
[1 entry added, 0 entries deleted, 1 entry modified]
```

### Repro Steps
Open a list of recent entries in your editor with the command above and add an additional entry between those.

### PR DESCRIPTION
**Pull request by piero-vic**
Fixes #1198. The summary used to show negative numbers when entries were added. There was also no option to show the added entries. 

### Checklist

- [x] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [x] I have included a link to the relevant issue number.
- [x] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [ ] I have written new tests for these changes, as needed.

### CODE REVIEW

**Review by micahellison — DISMISSED** [review]
Hi there, thanks for this contribution! I'd love to see some tests with this, though I recognize that haven't written any tests for this in the past.

We have two methods for testing this that could be fine - the normal pytest unit tests in tests/unit, or the pytest-bdd tests in tests/bdd. You're welcome to take either approach.

And if you're not interested in adding that in, that's absolutely okay. Just please let us know so we can take that on.

**Comment by piero-vic** [comment]
Hi. Thanks for the welcoming response. Unfortunately, I'm not familiar with testing in python. I would love to learn. Please feel free to add anything to the pull request. I will take a look at the changes and use them as an example for future contributions.

**Comment by micahellison** [comment]
OK, I added in some BDD (Gherkin) tests, though I excluded DayOne since it has its own way of dealing with this issue, which I think is beyond the scope of the PR.

I also ran into some cache issues (hence the failing tests in GitHub actions) but resolved them in #1373.

**Review by wren — APPROVED** [review]
🚀

**Pull request merged**
