### PR TITLE
Check for duplicate keys in config file

### LINKED ISSUE #1415: Warn user when there are duplicate keys in the config file
### Use Case/Motivation

If there are duplicate keys on the same level of the config file (e.g. "editor" shows up twice at the top level), our loader just picks one of them (currently the first, though I'm investigating replacing the loader with another loader that is picking the last). I think this is fine, and we should be permissive when it comes to loading the YAML file, but it would also be good to give some feedback to the user since this could be tough to troubleshoot otherwise.

### Example Usage

Maybe the warning could say something like: "Warning: the [key name here] key appears twice at the same level in your configuration file."

### Other information

It's NOT a problem if a key appears once at each level - for instance, if I have an "editor" specified at the top level, but a different "editor" specified for a particular journal. Don't warn the user in this case.

To resolve this issue:
- [ ] Add the warning when the config file loads
- [ ] Add BDD tests to ensure that the duplicate key warning:
  - [ ] appears with top level duplicates
  - [ ] appears with journal-level duplicates
  - [ ] does not appear with a value appearing once at the top level and once at the journal level
  - [ ] does not appear when using --config-override on an existing value
  - [ ] does appear when using --config-file to point to a config file with duplicate keys

### PR DESCRIPTION
**Pull request by jonakeys**
This PR solves issue #1415 It checks if a config file contains duplicate keys at the same level in the config file, warns the user about that and names the keys it concerns. The program still runs as usual (i.e. no exception is thrown) as stated in the requirements in the issue.
I also added BDD tests for the different cases.

Edit:
I chose to exclude old .json files, because those won't probably be used a lot anymore and besides that: after one run the config will be upgraded to .yaml anyway, so the check will be run.

Fixes #1415 

### Checklist

- [x] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [x] I have included a link to the relevant issue number.
- [x] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [x] I have written new tests for these changes, as needed.

### CODE REVIEW

**Review by wren — CHANGES_REQUESTED** [review]
Great addition of tests, and thenk you for taking on this issue, but the implementation itself is a bit brittle here. Instead of parsing the yaml file ourselves, can we make use of the yaml parsing library that jrnl already has loaded (ruamel)?

It looks like we already use `yaml.allow_duplicate_keys` [in config.py](https://github.com/jrnl-org/jrnl/blob/develop/jrnl/config.py#L165), so maybe we can make use of that? It might work to set `yaml.allow_duplicate_keys = False`, catch the exception, then warn the user about it, and reload with `yaml.allow_duplicate_keys = True` to be able to continue.

This would avoid reinventing a yaml parser, and give us a more robust check.

What do you think?

**Comment by jonakeys** [comment]
Thanks for your comments, I really appreciate it!
The solution you propose indeed is simpler/more robust in checking for duplicate keys. Ruamel can check for duplicate keys and than we can act on that. The reason I choose to find another way is because the issue said:

> Maybe the warning could say something like: "Warning: the [key name here] key appears twice at the same level in your configuration file."

And ruamel only returns _that_ the file has duplicates, but not _which_ keys are duplicate. I thought it would be helpful to give the user information about the key(s) it concerns.

If it's ok to warn the user the file has duplicates, but not mentioning them specifically, I'm happy to rewrite the code in the way you described it.

**Comment by wren** [comment]
> If it's ok to warn the user the file has duplicates, but not mentioning them specifically, I'm happy to rewrite the code in the way you described it.

Hrmm, that's a good point. Yes, I think that the increased robustness is worth the more vague warning. That's a shame that the exception doesn't have more info, but if that's the best we've got, then I think it's still worth using the library.

**Comment by wren** [comment]
@jonakeys Actually, I just did a quick test on this with `yaml.allow_duplicate_keys = False` and I see the following exception, which seems to have all the info we want:

```
┏━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  DuplicateKeyError                                                                                                                                              ┃
┃          while constructing a mapping                                                                                                                           ┃
┃    in "/Users/jonathan/Projects/Jrnl/test.yaml", line 14, column 5                                                                                              ┃
┃  found duplicate key "journal" with value "~/Projects/Jrnl/test-journals/basic_onefile.journal" (original value:                                                ┃
┃  "~/Projects/Jrnl/test-journals/basic_onefile.journal")                                                                                                         ┃
┃    in "/Users/jonathan/Projects/Jrnl/test.yaml", line 15, column 5                                                                                              ┃
┃                                                                                                                                                                 ┃
┃  To suppress this check see:                                                                                                                                    ┃
┃      http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys                                                                                               ┃
┃                                                                                                                                                                 ┃
┃                                                                                                                                                                 ┃
┃          This is probably a bug. Please file an issue at:                                                                                                       ┃
┃          https://github.com/jrnl-org/jrnl/issues/new/choose                                                                                                     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

```

Are you seeing something different?

**Comment by jonakeys** [comment]
The output you get is the output I get now myself too.. I can't recall seeing this when I started working on the issue. This is indeed enough information and a solution is close by. I'll see how to catch the exception and load the config after that.
Thanks for your ideas and thinking!

**Comment by jonakeys** [comment]
@wren I reworked the code. The warning message now looks like this:

```
(jrnl-aMUFJMGM-py3.9) jonathan@gentoo ~ $ jrnl -1

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃  Warning: One or more keys appear multiple times at the same level       ┃
┃          in your configuration file.                                     ┃
┃                                                                          ┃
┃          while constructing a mapping                                    ┃
┃    in "/home/jonathan/.config/jrnl/jrnl.yaml", line 2, column 3          ┃
┃  found duplicate key "title" with value "CYAN" (original value: "CYAN")  ┃
┃    in "/home/jonathan/.config/jrnl/jrnl.yaml", line 6, column 3          ┃
┃                                                                          ┃
┃  To suppress this check see:                                             ┃
┃      http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys        ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
2022-06-09 20:37 this is a new entry
```



I can't get the second line 'in your configuration...' start at the same indent as the first line. Do you know how to fix this?

**Comment by wren** [comment]
@jonakeys Thank you!

Since there's a beta out right now (v3.0), we're going to wait to fully review and merge this after that version is released. Thanks for your hard work on it! 👍

**Comment by jonakeys** [comment]
Glad I can contribute a little to this project!
I understand the v3.0 is around the corner, so it's wise to focus on that release.

**Comment by micahellison** [comment]
> I can't get the second line 'in your configuration...' start at the same indent as the first line. Do you know how to fix this?

I was just talking over this w/ @wren about this now, who will fix this in a separate PR for all messages by dedenting before building the message with its arguments.

**Review by wren — DISMISSED** [review]
Looks great. Thank you!

**Review by micahellison — APPROVED** [review]

**Pull request merged**
