### PR TITLE
Add Python 3.12 support

### LINKED ISSUE #1750: Add Python 3.12 support
### Use Case/Motivation

Python 3.12 beta is out and we should support this sooner rather than later. 3.12 final is expected to be released in October.

### Example Usage

n/a

### Other Information

_No response_

### PR DESCRIPTION
**Pull request by micahellison**
Fixes #1750. Adds Python 3.12 to continuous integration and updates sub-dependencies for 3.12 compatibility.

### Checklist

- [x] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/docs/contributing.md).
- [x] I have included a link to the relevant issue number.
- [x] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [x] I have written new tests for these changes, as needed.

### CODE REVIEW

**Comment by micahellison** [comment]
It looks like flakeheaven--or our particular setup--isn't ready for Python 3.12 beta. Replacing flakeheaven with ruff is also on my agenda right now so I'll leave this unresolved until that's taken care of.

**Comment by micahellison** [comment]
We're fine with linting now, but the next step is to deal with the ansiwrap issue in #1693.

**Comment by micahellison** [comment]
It looks like we have issues with two sub-dependencies:
 
* For some reason, `pyyaml` (dependency of `mkdocs`) downgrades from 6.0.1 to 6.0 on my machine when poetry is installing in Python 3.12. I don't know why. It's also a dependency of another `mkdocs` dependency `pyyaml-env-tag`, but both of their version specs should match 6.0.1. Here's the output from `poetry show --tree`:
```
|-- pyyaml >=5.1
|-- pyyaml-env-tag >=0.1
|   `-- pyyaml * 
```
* The `cffi` dependency of `cryptography` fails to install in Python 3.12. It looks like [they are still working on Python 3.12 compatibility](https://foss.heptapod.net/pypy/cffi/-/issues/565). 

I'll probably wait at least a couple more weeks before revisiting this. Once the deps are ready, we'll still have to address any potential new test failures.

**Comment by micahellison** [comment]
I still see the same problem with cryptography's sub-dependency cffi, though it looks like the maintainer is planning on fixing it soon.

**Comment by micahellison** [comment]
I don't think we'll be ready to support Python 3.12 by the October 2nd release date at this rate. The cryptography/cffi issue remains, though I do see that there is ongoing work on it upstream. I'll keep checking in the coming weeks.

**Comment by micahellison** [comment]
I resolved the pyyaml issue simply by running `poetry lock`. We don't run this often because renovate handles most of its functionality via PRs. However, it's been leaving the sub-dependencies untouched whenever possible, and some of these sub-dependencies like pyyaml and cffi needed to be updated for Python 3.12. With annual Python releases, I don't think we need to change our process to address this since they show up as failures in our Python version PRs and are appropriately fixed there.

**Comment by micahellison** [comment]
All the tests are passing in CI now, but jrnl will not work in a normal Windows environment with Python 3.12 right now.

I can't install jrnl on my Windows 10 machine because there are no wheels for ruamel.yaml's sub-dependency ruamel.yaml.clib. I [filed an issue](https://sourceforge.net/p/ruamel-yaml-clib/tickets/26/) in ruamel.yaml.clib and the maintainer is already aware of it. This problem leads to this error when I run `poetry install --sync`:
```
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

I am assuming that the CI build for Windows in Python 3.12 is green right now because the GitHub Actions Windows runner has all sorts of Microsoft build tools pre-installed. It must have built the sub-dependency. But we absolutely don't want to require these build tools for Windows jrnl users, so let's hold off until that wheel is available.

**Comment by micahellison** [comment]
Still waiting for a wheel from ruamel.yaml.clib, which doesn't have Python 3.12 Windows wheels because the Appveyor service that builds it doesn't support 3.12. I'll check back after the related issue is resolved: appveyor/ci#3879

**Comment by micahellison** [comment]
ruamel.yaml.clib just released the Python 3.12 Windows wheels, and it is installing just fine on my machine. This is ready for review now.

**Comment by EwoutH** [comment]
> Still waiting for a wheel from ruamel.yaml.clib, which doesn't have Python 3.12 Windows wheels because the Appveyor service that builds it doesn't support 3.12.

AppVeyor updated their images with Python 3.12 (https://github.com/appveyor/ci/issues/3879).

**Pull request merged**
