### PR TITLE
External Plugins v2

### PR DESCRIPTION
**Pull request by minchinweb**
(This is a follow up to #1115 because in that one I pushed directly to develop, plus it's been squashed and rebased, and it proved easier in my head to make a new branch.)

The open "issues" from #1115:

- [x] Tests: not included yet. Any ideas on how to change the installed Python packages in a "new" testing environment?
- [x] handling of name conflicts: Running `jrnl --version` will show you the list of active plugins, include where they came from.
- [x] display plugin version: Also on `jrnl --version`
- [x] documentation: Done!

Sample `jrnl --version` output:
```
λ jrnl --version
jrnl version v2.7.2-beta

Copyright (C) 2012-2021 jrnl contributors

This is free software, and you are welcome to redistribute it under certain
conditions; for details, see: https://www.gnu.org/licenses/gpl-3.0.html

Active Plugins:
    Importers:
        jrnl : v2.7.2-beta from jrnl.plugins.importer.jrnl_importer
    Exporters:
        boxed : v2.7.2-beta from jrnl.plugins.exporter.fancy_exporter
        fancy : v2.7.2-beta from jrnl.plugins.exporter.fancy_exporter
        json : v2.7.2-beta from jrnl.plugins.exporter.json_exporter
        markdown : v2.7.2-beta from jrnl.plugins.exporter.markdown_exporter
        md : v2.7.2-beta from jrnl.plugins.exporter.markdown_exporter
        tags : v2.7.2-beta from jrnl.plugins.exporter.tag_exporter
        text : v2.7.2-beta from jrnl.plugins.exporter.text_exporter
        txt : v2.7.2-beta from jrnl.plugins.exporter.text_exporter
        xml : v2.7.2-beta from jrnl.plugins.exporter.xml_exporter
        yaml : v2.7.2-beta from jrnl.plugins.exporter.yaml_exporter
```

For documentation, I would love to take insert the sample plugins from external files, and use those same external files as a base for the testing. Is the first part (inserting an external file) possible to MkDocs?

Also, the template exporter got dropped because I couldn't figure out how to make it work with displaying the version numbers... Is that okay?

### CODE REVIEW

**Comment by minchinweb** [comment]
Thanks to @sriniv27 for starting on the testing! See https://github.com/MinchinWeb/jrnl/pull/3

I've moved the external plugins to be used in testing into the repo tree, so there won't be a need to maintain a separate repo/package, and the code can directly be used as an example in the docs.

GitHub workflows is set up (I think) to run the test suite twice: once with only the built-in plugs and a second time with the extra override plugins. However, I can't get GitHub Actions to run, so I'm not sure what's currently working and what's broken.

The fixes of https://github.com/jrnl-org/jrnl/pull/1219 may also need to be manually merged in.

@wren @micahellison Can you enable GitHub Actions or otherwise help me figure out why they aren't working? Also, I think this is at the point where if you could look over what testing is here and let us know if there is something in particular that has been missed, that would be helpful.

**Comment by micahellison** [comment]
> @wren @micahellison Can you enable GitHub Actions or otherwise help me figure out why they aren't working? Also, I think this is at the point where if you could look over what testing is here and let us know if there is something in particular that has been missed, that would be helpful.

Hi @MinchinWeb, I've confirmed that actions are enabled and allowed, though from some research it looks like they won't run when there are merge conflicts with the target branch. Could you try resolving the merge conflicts and seeing if that allows actions to run?

**Comment by micahellison** [comment]
@MinchinWeb I'm looking through this and I like your dev documentation. Not quite ready to do a deep dive but the `jrnl/plugins/meta.py` file is jumping out at me. Could you document the responsibility of that file in its source? And possibly rename it to be a bit more specific? I'm not sure what the best vocabulary is for it -- maybe "plugin collector" or something along those lines?

**Comment by minchinweb** [comment]
@micahellison I got the merge conflicts resolved, so testing is working again! That said, GitHub could use some better indication of of what's going on....

---

Latest changes:

- resolved merge conflicts; tests on GitHub work again!
- "short" and "pretty" formats are now regular exporters. This creates less special cases, and also allows them to be overridden.

Open issues:

- <strike>on GitHub Actions, the Windows tests aren't installing the plugins because the environmental variables are either called something else or unavailable. (The test plugins are installed from `git+${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git@${GITHUB_SHA}#egg=jrnl-demo-plugins&subdirectory=tests/external_plugins_src`). Perhaps this can be solved by installing them from the already-downloaded git repo</strike> solved!
- on Ubuntu, I can't tell whether the tests are being run with the plugins installed or not (because the number of skipped tests is the same). Do I need to do something special to make sure they're in the environment *behave* is using?
- <strike>the version in `features/plugins.features` is currently hardcoded, but it needs to update as the reported version of *jrnl* changes.</strike> solved!

**Comment by minchinweb** [comment]
@micahellison Re *meta*: the term is used in the reflexive sense, meaning it has to do with the thing itself, like certain French verbs (*je me rase*, literally "I shave myself"), or how *metacongnition* is the thinking about thinking. Here's what I added to the file header to explain my thinking:

> This file ("meta") uses that title in the reflexive sense; i.e. it is the
collection of code that allows plugins to deal with themselves.
>
>In particular, the code here collects the list of imports and exporters, both
internal and external, and tells the main program which plugins are available.
Actual calling of the plugins is done directly and works because given plugin
functions are importable/callable at predetermined (code) locations.
>
>Internal plugins are located in the `jrnl.plugins` namespace, and external
plugins are located in the `jrnl.contrib` namespace.

I'm not opposed to another filename, but, to me anyway, it seemed like the most accurate name.

**Comment by micahellison** [comment]
> In particular, the code here collects the list of imports and exporters, both
> internal and external, and tells the main program which plugins are available.

Hi @MinchinWeb, thanks for adding this documentation. I think that it would be better to refer to this as a "plugin collector" rather than as "meta" still. While it's true that it is "meta", "plugin collector" specifies its responsibilities and is therefore more resistant to shearing against the single responsibility principle over time. It's the same reason we removed that old "util" file -- all its contents were technically utilities, yes, but it's the responsibilities that are more important when it comes to organizing code for maintainability.

**Comment by minchinweb** [comment]
@micahellison The *meta* file has been renamed.

**Comment by minchinweb** [comment]
Today's progress:

- I discovered that behave cannot be run from the project's root directory and recognize the installed test plugins
    - I reorganized some of the behave test code not to rely on local imports (so it can be run outside the project folder)
    - I've tried a number of ways to get this to work (running from not the root directory), and the best I could figure was to manually create and activate the virtual environment
- Template code is completely gone. However, I realized that you could probably make a custom importer that is interactive, which, I think, was what the template code was trying to do

I think we're ready to merge. Please review and let me know if there is anything outstanding! @wren @micahellison

**Comment by minchinweb** [comment]
Ok, maybe I jumped too soon. The remaining issue is how to get the tests to run of GitHub, and **not** from the root directory (which is what *poetry run* seems to assume). I'm at a loss at the moment...

**Comment by wren** [comment]
What's going on? Sorry, I haven't been watching this particular PR closely (it's mostly Micah's jam). But yeah, pretty much everything about our test suite assumes the root directory (as you've noticed). Why do we need to change the directory? I see a comment about plugins not being detected. Do we know why that is?

**Comment by minchinweb** [comment]
OK, tests work and they pass! Hallelujah! I won't claim that it's beautiful, but it works, and I'm happy with that.

@wren
> Why do we need to change the directory? I see a comment about plugins not being detected. Do we know why that is?

I think this is a combination of the plugins being namespace plugins and the main jrnl source being locally importable from the project root folder. Namespace plugins work be creating a "virtual" module out of several physical locations on disk; when importing the jrnl module from the project root (rather than from the site-packages folder where it's installed by pip), these namespace modules aren't recognized as namespace modules, and instead come up as empty.

To test this:

~~~shell
# navigate to the project root folder
# create a virtual environment and activate it
python -m venv .venv-test-plugins
source .venv-test-plugins/bin/activate
# on Windows: .\.venv-test-plugins\Scripts\activate
# install jrnl
pip install .
# install the test plugins
pip install ./tests/external_plugins_src/
# install behave
pip install behave
# run behave; note the number of steps completed
behave --format progress2
# 1738 steps passed, 0 failed, 163 skipped, 0 undefined
# now change up a folder and rerun behave
cd ..
behave --format progress2 ./jrnl/features
# 1664 steps passed, 0 failed, 237 skipped, 0 undefined
~~~

---

In any case, I think we're ready to merge! @micahellison

**Comment by micahellison** [comment]
Thanks @MinchinWeb! I see this is ready for review, and I'll plan on diving into this in a week. Also, we won't merge anything big in before that so there won't be any more major merge conflicts to deal with.

**Comment by micahellison** [comment]
Hi @MinchinWeb, I'm reviewing this while educating myself on namespace packages [here](https://packaging.python.org/guides/packaging-namespace-packages/) and I see that there are three different approaches for namespace packages, but I can't tell which is being used in this PR. Or is there a completely different approach that it's using, and if so, what's the advantages of it?

**Comment by minchinweb** [comment]
Hi @micahellison These are "native namespace packages" (the first option mentioned on the page you link to).

Why this way? It seems to be the most "modern" option, and beyond getting the plugin files in the right place, there should be no packaging boilerplate for plugin authors.

**Comment by micahellison** [comment]
Got it, thanks. I agree that it makes sense -- I was just confused that the form of the sample plugin looked a little different from the documentation I linked. Then I learned more about `__init__.py` than I ever thought there was to know...

Along those lines, I'm chatting about this with @wren and we think we have a solution to this folder issue you documented, by removing the two `__init__.py` files from jrnl and moving their functionality elsewhere. We should have a patch coming in a bit.

**Comment by micahellison** [comment]
Actually, we're going to merge this into a feature branch so we can work on it a bit more asynchronously.

**Review by micahellison — APPROVED** [review]
✨🔌✨

**Comment by minchinweb** [comment]
@micahellison I'm curious about what more needs to be done/what else you want in place before merging this to master...

**Comment by wren** [comment]
cc: #1006

**Comment by micahellison** [comment]
Hi @MinchinWeb sorry for the slowness on this -- it's been a busy month. I just put [my notes in the linked issue](https://github.com/jrnl-org/jrnl/issues/1006#issuecomment-864452317).

**Comment by wren** [comment]
@MinchinWeb Quick note: jrnl doesn't have a branch named `master` anymore. We renamed our main branches a while back to `develop` and `release` (where `develop` is the default branch that all PRs are pointed to) to avoid using language that could be hurtful to some people.

**Pull request merged**
