### PR TITLE
Allow editing of DayOne entries (#955)

### LINKED ISSUE #955: [DayOne] Editing an entry shows AttributeError
- Jrnl version: **2.4.2**
  - How you installed Jrnl: **pip3 install jrnl**
  - Operating system: **MacOS**

I’m using [DayOne Classic integration](https://github.com/jrnl-org/jrnl/blob/f0f26a18eb3304aff5ea53e669802a18a2f85e5a/advanced/index.html#L194) with iCloud synchronization.

Trying to edit an existing entry. No modifications made to the text itself. Tried with multiple editors (`vim`, `sublime`). Always ending up with error message **AttributeError: can't set attribute**.

```
fbreunig@nighttrain:~ $ jrnl --version
jrnl version v2.4.2
fbreunig@nighttrain:~ $ echo test | jrnl
[Entry added to default journal]
fbreunig@nighttrain:~ $ jrnl -n 1 --edit
Traceback (most recent call last):
  File "/usr/local/bin/jrnl", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/jrnl/cli.py", line 460, in run
    journal.parse_editable_str(edited)
  File "/usr/local/lib/python3.7/site-packages/jrnl/DayOneJournal.py", line 150, in parse_editable_str
    current_entry.title = line[len(date_blob) - 1 :]
AttributeError: can't set attribute
```

Note: If I delete the _entire_ text during editing, the entry is being deleted as expected:
```
[Nothing saved to file]
[1 entry deleted]
```

### PR DESCRIPTION
**Pull request by minchinweb**
This allows DayOne entries to be edited by *jrnl*.

It includes a basic test (thanks **wren**! #989) that makes sure this is possible without errors, but there is still no test that shows that the edits are actually being consumed properly (I'm not sure how to add such a test). That said, this has been testing locally, and appears to be working.

Fixes #955. Closes #955. Closes #989.

### Checklist

- [x] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [x] I have included a link to the relevant issue number.
- [x] I have tested this code locally.
- [x] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [x] I have written new tests for these changes, as needed.
- [x] All tests pass.

### CODE REVIEW

**Comment by micahellison** [comment]
I'm running this with `poetry shell` and it looks like it's erasing the title of the entries that it's editing.

Here's a quick test using the dayone.dayone journal in the features/data folder:

```
> jrnl -1
2013-07-17 11:38 This entry is starred!

> jrnl --edit -1
```
Then using my editor, I add a line:

```
# 422BC895507944A291E6FC44FC6B8BFC
[2013-07-17 11:38] This entry is starred! *
I'm adding a line
``` 

Then back to the command line, you can see the title disappearing:
```
> jrnl -1
2013-07-17 11:38 I'm adding a line
```

**Comment by micahellison** [comment]
I added a test for this issue with PR #993.

**Comment by minchinweb** [comment]
@wren @micahellison So I've been messing with this, but I'm a little confused by the [Entry](https://github.com/jrnl-org/jrnl/blob/develop/jrnl/Entry.py) class. In particular, it has members/properties `text`, `fulltext`, `body`, and `_body`, but it seems to me that these basically refer to the same thing. Are either of you familiar in what the differences between these are meant to be?

**Comment by wren** [comment]
I haven't really done much work on `Entry`, but looking at it, here's what I see:

- `text` is the user input, before it's parsed out to a proper entry
- `body` is a property of the entry parsed out out of `text` (same as `title`)
- `_body` is the class' internal representation of `body` (like `_title` and `_tags`)
- `fulltext` looks like a convenience property to get the `title` and `body` at the same time, and seems to not really be in use (only by the xml exporter)

**Comment by wren** [comment]
Merged into #1001

**Pull request closed without merging**
