### PR TITLE
[WIP] Fix compatibility with pytest-bdd 6

### LINKED ISSUE #1534: Support pytest-bdd 6
### Use Case/Motivation

[Version 6.0 of pytest-bdd has been released with numerous breaking changes](https://github.com/pytest-dev/pytest-bdd/releases/tag/6.0.0).

### Example Usage

https://github.com/jrnl-org/jrnl/pull/1531

### Other information

Almost everything fails when I do a quick compatibility check. I haven’t had a chance to investigate, but I wanted to go ahead and open this bug to track the situation.

https://github.com/pytest-dev/pytest-bdd/issues/501 seems to be popping back up in the CI for https://github.com/jrnl-org/jrnl/pull/1531; not sure if that is related to the `pytest-bdd` update or not.

### PR DESCRIPTION
**Pull request by felixonmars**
Fixes #1534 

### Checklist

- [x] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [x] I have included a link to the relevant issue number.
- [x] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [ ] I have written new tests for these changes, as needed.

### CODE REVIEW

**Comment by felixonmars** [comment]
I am trying to invoke `inject_fixture` manually to simulate the behavior in prior to https://github.com/pytest-dev/pytest-bdd/pull/493 , but turns out it's more complex than I thought. This remains a WIP for now.

**Comment by micahellison** [comment]
Thanks @felixonmars for picking this up! Let us know if you have any questions or want to talk anything through.

**Comment by micahellison** [comment]
Hi @felixonmars, I'm closing this since it has gotten stale and we've been working on this elsewhere, but we'll be sure to include you as a co-author for your initial work on this.

**Comment by felixonmars** [comment]
Thanks! Indeed I'm having trouble understanding the remaining issues and didn't have any progress in the past months. Sorry for that!

**Pull request closed without merging**
