### PR TITLE
[Dayone] remove extra spaces from the titles of edited DayOne entries

### PR DESCRIPTION
**Pull request by MinchinWeb**
Otherwise, a leading space was being introduced

### CODE REVIEW

**Comment by MinchinWeb** [comment]
Now also maintains existing metadata (location, weather, creator) on Dayone entries across edits.

**Comment by MinchinWeb** [comment]
Manually resolved merge conflict with #355

**Comment by flight16** [comment]
Thanks for the leading space fix.  I encountered this issue, too.  Looking forward to it getting merged back into the 2.0 branch.

**Comment by wren** [comment]
Is this PR still relevant? It seems like fixes for Day One before their 2.0 is outdated, but I honestly don't know if people still use the older Day One client.

**Comment by MinchinWeb** [comment]
@wren I actually use a DayOne Classic compatible client on Windows. (DayOne has never released official client for Windows).

**Comment by wren** [comment]
@MinchinWeb Which client? Are there any similar client for Mac? Do you know if Day One supports their old client anymore?

**Comment by MinchinWeb** [comment]
I'm using [Journaley](https://github.com/yyoon/Journaley). I don't have a Mac, so I've never gone looking for something similar there. I rather doubt Day One is still supporting their old clients; it seems they haven't updated it to work with Dropbox's new API.

This also helps with old entries, written in the original DayOne (iPad/iPhone) client when it was still current.

**Comment by MinchinWeb** [comment]
@ wren this has been rebased against the current master, add all test are passing. It should be ready to be merged!

These are all bug fixes, so I'd love it if it made the 2.0 cutoff.

**Comment by MinchinWeb** [comment]
We may need to review what we're doing with line endings. This is one of the raw strings that was being testing against:

`'2010-06-10 15:00 A life without chocolate is like a bad analogy.\r\n\n2013-06-10 15:40 He said "[this] is the best time to be alive".\r'`

(notice the total mis-match of line endings.) Some of it, I'm sure, is due to Windows, and some due to Git, but it was making for tests that passed on Travis, but failed locally.

**Comment by wren** [comment]
I'm going to close this for a bit, while we wait for the day one-related tests to come back.

**Pull request closed without merging**
