### PR TITLE
Add --delete for interactive removal of entries

### LINKED ISSUE #434: --delete ?
Instead of using --edit then delete/save/quit editor, maybe it would be easier to have a --delete command that would show the selected entries and ask confirmation to delete them, without going through the editor.
Especially convenient when managing todo lists.

$ jrnl @todo buy bread
$ jrnl @todo wash dishes
$ jrnl @todo --delete # I'm done with today's duty
2016-07-30 11:43 @todo buy bread

2016-07-30 11:43 @todo wash dishes

Are you sure you want to delete the selected entries? [y/N]

(And jrnl is a great app by the way!!)

### PR DESCRIPTION
**Pull request by alichtman**
- Add switch for deleting entries. Works with filters, etc.
- Fix some minor style issues

Fix #434

```bash
# First, create a journal named "test"
$ python3 -m jrnl test First entry
$ python3 -m jrnl test Second entry
$ python3 -m jrnl test Third entry
$ python3 -m jrnl test --delete
```

### Checklist
- [x] The code change is tested and works locally.
- [x] Tests pass. Your PR cannot be merged unless tests pass
- [x] There is no commented out code in this PR.
- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your core changes, as applicable?

### CODE REVIEW

**Comment by alichtman** [comment]
Turns out the python library I used for prompting doesn't support windows: https://github.com/magmax/python-inquirer/issues/63

I could load an alternative library in that case, disable the feature, or find a different library that works on all platforms.

**Comment by alichtman** [comment]
```cucumber
    # The input for this test is <SPACE><ENTER>y
    Scenario: --delete flag allows deletion of single entry
        Given we use the config "deletion.yaml"
        When we run "jrnl --delete"
        And we type " "
        And we type
            """

            y
            """
        When we run "jrnl -on 2019-10-29 -s"
        Then the output should not contain "2019-10-29 11:11 First entry."
```

This structure for the test doesn't work... Testing this feature as it is may not be possible.

image

**Comment by peter-schmidbauer** [comment]
PyInquirer seems like a heavy dependency for a relatively simple feature like this. 
Also, your PR adds another place which parses datetimes without using config["timeformat"], which we should try to avoid as time.parse() doesn't work with all formats. 

Why don't we just do it like `rm -i` and keep it simple?
Something like:

```python
def prompt_delete_entries(entries: List[Entry]):
  print("Confirm each entry you want to delete [N/y]:")
  to_delete: List[Entry] = []
  for entry in entries:
    agreed = input("jrnl: Delete entry '{}'? ".format(entry.pprint(short=True)))
    if agreed == "y":
      to_delete.append(entry)

  return to_delete
```

And then: 

```python
jrnl.entries = [e for e in jrnl.entries if e not in to_delete]
jrnl.write()
```

That would also be much easier to test.

**Comment by alichtman** [comment]
I believe it's a much better user experience with the interactive selection provided by `PyInquirer`. If I want to quickly scan a list of potentially hundreds of journal entries and select only one or two to delete, I'd much rather have the selection checkbox than have to [y/n] every single entry up until the one I'd like to remove.

**Comment by alichtman** [comment]
> Adding a complete command-line UI just for `--delete` creates an inconsistent user experience in my opinion.

I see a natural progression to using this with `--edit`, as well. Any features that involve selecting some subset of journal entries before performing some other action with them (aside from maybe viewing) should have a nice selection UI.

**Comment by alichtman** [comment]
> your PR adds another place which parses datetimes without using config["timeformat"], which we should try to avoid as time.parse() doesn't work with all formats.

This is a fair point though. I have to take a closer look at how to handle this.

**Comment by peter-schmidbauer** [comment]
I may be wrong, but I think the main use case for this would be to delete the last entry. This would be very easy with my proposal, especially when adding a `-y|--yes` option to skip the questions:
`jrnl -1 --delete -y`

It might even make sense to make that the default when none of the selection options are specified (instead of putting up the whole journal for deletion). 

If you are looking for a specific text to delete in the journal then the feature proposed in #463 would help. But if you need to really scan through the whole thing then maybe just going with `jrnl --edit` and dealing with it in your editor would be the better choice anyways.

Sorry if I'm being a downer here, I'm just personally not a big fan of 'GUIifying' a CLI ;)

**Comment by alichtman** [comment]
> Even if you are looking for a specific entry, then you probably saw that entry earlier and can look for it using its date

I'd rather combine these steps into one command. Instead of going fishing for an entry, copying the date or a tag or something, and then running `jrnl <search> --delete`, I'd like to start fishing from `jrnl --delete`.

> But if you need to really scan through the whole thing then maybe just going with jrnl --edit and dealing with it in your editor would be the better choice anyways.

I'm always scared of deleting partial entries / more than I want to when I pull up the raw journal to edit in vim. I always have to scan what I'm deleting multiple times just to be sure...

One nice aspect of the interactive selection option is that it's not possible to delete partial entries / corrupt the journal. Your solution works for small lists of entries, but I'd prefer mine for larger lists.

I do understand your concerns, however. Still thinking about how to best handle this. It'd be great to get some input from other contributors and users.

**Comment by wren** [comment]
This is a tough one. I think the introduction of an interactive UI is a bit too much for now, but you raise some very good points about how cumbersome it can be to deal with querying large amounts of journal entries for the right ones to delete. I need to think about this one a bit more.

@micahellison What do you think?

**Comment by micahellison** [comment]
I'm of a couple minds about this also. I was about to post that we should use filtering rather than an interactive tool, but then it hit me that one reason to delete an entry could be that a duplicate was made on the same specified time. No amount of filtering could rule out that duplicate, right? Having an entry-by-entry confirmation could deal with that situation, but it could also be really annoying for when a user is really sure that they want to delete a range of entries.

And yet, maybe this is what editing is for. After all, people have already been using this tool for seven years, and the edit functionality has been the way to do this. Maybe `--delete` could be for the simple use cases (such as the most recent entry, as @pspeter mentioned), and we recommend users use edit for more complicated situations.

As an aside, I think there is a place for interactive UIs that interact with jrnl and/or jrnl's data. I would love for this tool to be easily available for people that aren't comfortable with the command line. But I think we should take great care in figuring out their points of contact with jrnl (e.g. a plugin system), and setting them up in a way that minimizes their impact on jrnl's core functionality. So even with tricky use cases like the above, my instinct is to lean away from interactivity.

**Comment by alichtman** [comment]
> But I think we should take great care in figuring out their points of contact with jrnl (e.g. a plugin system), and setting them up in a way that minimizes their impact on jrnl's core functionality.

I would agree that having a plugin system is probably the right way to go with this. Also, I'm excited to build a plugin system, so there's that :)

What if we have filtering with confirmation by default (somewhat along the lines of @pspeter's solution), and offer an interactive deletion plugin. Anyone that doesn't want to use it doesn't have to.

**Comment by wren** [comment]
Yup, sounds good! We can have a `--delete` option (no gui) with a prompt to confirm, with a `--force` (no one-letter option for now).

**Comment by alichtman** [comment]
Ah... yeah that rebase doesn't look right. I'm going to have to figure out how to get this all fixed up. 😨

**Comment by alichtman** [comment]
Still needed:

- Tests
- `--force` option

**Comment by wren** [comment]
We can split the `--force` flag into a separate PR, if you'd like.

**Comment by alichtman** [comment]
Yeah, let’s do that.

**Comment by wren** [comment]
@alichtman Hi! This PR still looks really promising. Are you planning on coming back to it? Or would you like someone else to pick it up?

**Comment by alichtman** [comment]
If someone else could take it from where I left off, that'd be great. I've got a lot on my plate at the moment and can't fit this in, but this feature definitely deserves to get finished.

**Comment by wren** [comment]
@alichtman No worries. Thanks for taking it this far!

**Comment by dbxnr** [comment]
@alichtman Would you be interested in collaborating on a fork of the project? This seems like a really good feature and I'd like to do some more work on it with you

**Comment by wren** [comment]
@dbxnr Hi! As this is an open-source project, you're well within your rights to fork the project and do what you'd like with it. But please don't use our project's space to recruit for--or advertise--your other project. It's distracting for us here, and bad open-source community etiquette.

**Comment by alichtman** [comment]
> This seems like a really good feature and I'd like to do some more work on it with you

@dbxnr, if you're interested in improving this feature, I'd recommend opening another PR (since this one was just merged).

**Pull request merged**
