### PR TITLE
Add documentation about information leaks in Vim/Neovim 

### PR DESCRIPTION
**Pull request by Granddave**
### Checklist

- [x] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [ ] I have included a link to the relevant issue number. *(found none)*
- [x] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [ ] I have written new tests for these changes, as needed. *(not needed)*

This PR aims to increase the knowledge about "leaky editors" and how to mitigate that risk. I have only experience in Vim-like editors, but this could be a base for future docs about other editors as well.

### CODE REVIEW

**Comment by wren** [comment]
@Granddave This is great information. Thank you!

I'm wondering if it's worth pointing out how to disable these settings without completely disabling user config. I've seen some people use an autocommand to set something like:
```vim
autocmd BufNewFile,BufReadPre *.jrnl setlocal noswapfile noundofile nobackup nowritebackup viminfo= shada=
```

Do you think this would be sufficient to mitigate the security concern while not degrading the editor experience as much as `-u NONE`?

**Comment by Granddave** [comment]
Hi, sorry for the delay.

I'm no Vim expert but I think that starting Vim/Neovim with `-i NONE -n` is equivalent with setting `noswapfile viminfo=` for Vim and `noswapfile shada=` for Neovim so there seem to exist other leaky configs as you pointed out. Adding an autocommand might be easier to cover more cases.

But yes, disabling the whole config as well as having the autocommand disable some leaky options might be unnecessary, but IMO good to mention as an option for extra security.

I'll look into crafting a autocommand that we can use for the documentation for Vim and Neovim.

**Comment by wren** [comment]
@Granddave No worries about the delay. Just update here, or open a new PR whenever you're ready. Thank you!

**Comment by Granddave** [comment]
@wren, thanks!

I've pushed a fixup commit on this same branch with updated startup options as well as adding autocommands. Let me know what you think and I'll squash later if we decide to merge. :)

**Comment by Granddave** [comment]
@wren Ping

**Comment by wren** [comment]
> @wren Ping

I completely lost track of this since the PR is closed, sorry!

Would you mind opening a new one so we can go over it on Saturday?

**Comment by Granddave** [comment]
No worries :)

**Pull request closed without merging**
