### PR TITLE
In Encryption docs, explain how to prevent Fish history logging

### PR DESCRIPTION
**Pull request by roryokane**
This will modify http://jrnl.sh/encryption.html.

I use the [fish shell](https://fishshell.com/), so I had to look this up for myself. Might as well share it.

### CODE REVIEW

**Comment by wren** [comment]
@roryokane This looks good. Can you please rebase onto master to fix the file conflicts?

**Comment by roryokane** [comment]
Rebased. Also, the original commit had some grammar fixes mixed in, some of which were obsolete, so I made a separate commit with the grammar fixes that are currently needed.

**Comment by wren** [comment]
@roryokane One more thing, sorry! We moved the documentation to use markdown files instead of the rst. Can you move your changes to the markdown file?

**Comment by roryokane** [comment]
I redid the changes in the Markdown file.

**Pull request merged**
