### PR TITLE
Move test suite to Pytest (replace Behave)

### LINKED ISSUE #1192: Move test suite entirely to Pytest (replace Behave)
## Feature Request

I'd like to move our integration tests into Pytest (from Behave). We currently are using Pytest entirely for unit tests (which we need more of, but that's separate conversation). Rather than splitting our test suite between Pytest and Behave, I'd like to move our current feature files to Pytest (via [pytest-bdd](https://pypi.org/project/pytest-bdd/)).

### Use Case/Motivation

We've had some problems with Behave, and it's not as well maintained as we'd like. There is a pytest plugin (pytest-bdd) which is actively maintained, and supports the gherkin syntax that our feature files are already written in. It'll still require rewriting the python that currently powers Behave, but it'll give us a much more stable and feature-rich testing environment.

### PR DESCRIPTION
**Pull request by wren**
Fixes #1192

Moves test suite entirely into pytest from behave.

### CODE REVIEW

**Comment by micahellison** [comment]
I'm getting some IO and recursion errors while running these on Windows. These repeats a ton:
```
 Traceback (most recent call last):
    File "c:\users\micah\.pyenv\pyenv-win\versions\3.8.2\lib\tempfile.py", line 803, in onerror
      _os.unlink(path)
  PermissionError: [WinError 5] Access is denied: 'C:\\Users\\micah\\AppData\\Local\\Temp\\tmpyzro5wbt'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "c:\users\micah\.pyenv\pyenv-win\versions\3.8.2\lib\shutil.py", line 617, in _rmtree_unsafe
      os.rmdir(path)
  PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\micah\\AppData\\Local\\Temp\\tmpyzro5wbt'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "c:\users\micah\.pyenv\pyenv-win\versions\3.8.2\lib\tempfile.py", line 803, in onerror
      _os.unlink(path)
  PermissionError: [WinError 5] Access is denied: 'C:\\Users\\micah\\AppData\\Local\\Temp\\tmpyzro5wbt'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "c:\users\micah\.pyenv\pyenv-win\versions\3.8.2\lib\shutil.py", line 617, in _rmtree_unsafe
      os.rmdir(path)
  PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\micah\\AppData\\Local\\Temp\\tmpyzro5wbt'

  During handling of the above exception, another exception occurred:
```
And at the end, I get:
```

 RecursionError: maximum recursion depth exceeded while calling a Python object

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

**Comment by minchinweb** [comment]
As a headsup, I discovered today that the current behave test suite does not run as expected (at all?) if not run from the project root folder.

**Comment by micahellison** [comment]
Let's move off of pyflakes, probably to pylint, maaaaybe to flake8, though pylint looks better at first glance.

**Review by micahellison — APPROVED** [review]
🧪

**Pull request merged**
