### PR TITLE
Fixed error related to display_format in config file for some values

### LINKED ISSUE #1263: display_format: pretty and display_format: short lead to crash
### Environment
  - `jrnl --diagnostic` output: 
```
jrnl: v2.8.1
Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
OS: Windows 10
```
  - Install method:  pipx

### Current Behavior

Setting the `display_format` configuration operation to `pretty` or `short` causes jrnl to crash when viewing the contents of the journal.

### Expected Behavior

It should use the selected format instead of crashing.

### Other Information

Stack trace is the same whether on `pretty` or `short`:
```
Traceback (most recent call last):
  File "c:\users\micah\.pyenv\pyenv-win\versions\3.8.2\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\micah\.pyenv\pyenv-win\versions\3.8.2\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\micah\.local\bin\jrnl.exe\__main__.py", line 7, in <module>
  File "c:\users\micah\.local\pipx\venvs\jrnl\lib\site-packages\jrnl\cli.py", line 35, in cli
    return run(args)
  File "c:\users\micah\.local\pipx\venvs\jrnl\lib\site-packages\jrnl\jrnl.py", line 73, in run
    search_mode(**kwargs)
  File "c:\users\micah\.local\pipx\venvs\jrnl\lib\site-packages\jrnl\jrnl.py", line 179, in search_mode
    _display_search_results(**kwargs)
  File "c:\users\micah\.local\pipx\venvs\jrnl\lib\site-packages\jrnl\jrnl.py", line 340, in _display_search_results
    print(exporter.export(journal, args.filename))
AttributeError: 'NoneType' object has no attribute 'export'
```

### PR DESCRIPTION
**Pull request by apainintheneck**
### Checklist

- [x] I have read the [contributing doc](https://github.com/jrnl-org/jrnl/blob/develop/CONTRIBUTING.md).
- [x] I have included a link to the relevant issue number.
- [x] I have checked to ensure there aren't other open [pull requests](../pulls)
  for the same issue.
- [x] I have written new tests for these changes, as needed.

Basically what was happening was that using `display_format: pretty` or `display_format: short` in your config file would cause an error. The reason for this was that even though those arguments were handled correctly they were sourced from the config file after those if statements had already been skipped over.

Now `_display_search_results` tries to source the `display_format` value from the config file if the `export` arg is empty before displaying search results. This is a small change so I didn't include any tests. Let me know if you think they are necessary and I'd be happy to add them.

Fixes #1263.

### CODE REVIEW

**Comment by apainintheneck** [comment]
Actually, it looks like this clobbers the `--tags` flag so I'll take a longer look at it.

**Comment by apainintheneck** [comment]
Okay, I had to change it to evaluate `--tags` before `--format`. Also, there was a weird thing that showed up in the unit tests where `mock_args.tags` was evaluating to true so I changed that as well. The funny thing is that that test isn't even testing for tags so I'm not sure why that happened.

**Review by wren — APPROVED** [review]
Looks good! Just updated the unit test to fix the tags issue you were running into.

**Review by micahellison — APPROVED** [review]
Looks good! I just added a BDD test in case of regressions.

**Pull request merged**
