### PR TITLE
Pretty print journal entries (add color)

### PR DESCRIPTION
**Pull request by wren**
This was stuck in a temp branch due to our old merging strategy. We need to get everything into develop and master asap or we'll just end up with ever-increasing merge conflicts.

### Checklist
- [x] The code change is tested and works locally.
- [ ] Tests pass. Your PR cannot be merged unless tests pass
- [ ] There is no commented out code in this PR.
- [ ] Have you followed the guidelines in our Contributing document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?

### CODE REVIEW

**Comment by alichtman** [comment]
Any update on this?

**Comment by wren** [comment]
@alichtman Been focusing on the Homebrew release, but I have some time set out this weekend to go through the open PRs.

**Comment by wren** [comment]
The failing test on this is caused by `process_ANSI_escapes` on windows (since windows paths have baskslashes.

**Comment by alichtman** [comment]
Are you sure that's the right root cause? I'm having some trouble tracing the issue back to that function.

**Comment by wren** [comment]
I thought so, but I'll take another look at it tomorrow. I had a version of the test that was passing on Windows, and the only difference was that function wasn't being invoked for the test.

**Comment by wren** [comment]
@alichtman I got rid of the function and everything seems to be working properly now. Do you remember why this function was there? Is it required?

**Comment by alichtman** [comment]
I added that function because some tests were failing, relating to Unicode and ANSI escapes, and that fixed the problem. If they’re no longer failing, it’s no longer needed.

**Comment by alichtman** [comment]
Thanks for helping get this merged in! Know when develop will be merged into master?

**Pull request merged**
