### PR TITLE
Add ability to search in entry title and body

### LINKED ISSUE #384: List of --short entries on a full text search query on a journal
It would be nice if there was a full text search feature which returned just a short listing of entries. While I realize you can _kinda_ get a proxy for this with something like `jrnl -n 10 | grep awesome` or the like with the addition of the `|` in front of the entries is not quite what I'm going for. I'm looking 

Effectively, is there a way to get the equivalent of a full text search switch (much like tags) which returns a list of --short entries  where the search terms is in the body (or title of the jrnl entry).

ie. something like

```
jrnl -n 3 --short --search "awesome"
```

which yields a list 

```
2015-11-10 23:10 This entry mentions awesome in the title.
2015-10-10 22:12 This one only mentions it in the body of the text.
2015-09-09 20:12 This entry mentions it only in passing.
```

For some weird reason, this feels like a major missing feature (though, of course, it probably is only an issue for those of us using encryption and not being total fans of grep.  =p 

Daryl.
PS> If I've just missed something obvious in terms of getting this output with a command line pipe, do let me know. Have not had anywhere near enough coffee this morning.

### PR DESCRIPTION
**Pull request by radomirbosak**
This merge request replaces #448 , which wasn't rebased against branch `2.0-rc1`.

* The first commit fixes behave tests for `python3`.
* The second commit adds a feature to search the journal entries (their title and text body) by using the `-S` and `-search` CLI switches. (`-s` is already used for `--short`)

Fixes #384

### CODE REVIEW

**Comment by maebert** [comment]
I like that, but what's the rationale for using `-p` as a shorthand? Any other applications that are using this?

**Comment by maebert** [comment]
This looks great, but what's the rationale for using `-p` as a shorthand?

**Comment by radomirbosak** [comment]
I was thinking `-p` as in **p**lain search or **p**hrase (as suggested in #313 ). My first choice would be naturally `-s`, but that one is already used. Feel free to suggest/change the searching shorthand to anything else.

Other option would be using `-S` for search. What do you think?

**Comment by radomirbosak** [comment]
Ok, I changed the short option for search from `-p` to `-S`. I think it makes more sense.

**Comment by craftyguy** [comment]
Is there any chance of seeing this in a release soon? I've been using it, and it works great.

**Comment by empireshades** [comment]
This seems to fail only on the python 2.7 tests. In light of it being end of life'd ([https://www.anaconda.com/end-of-life-eol-for-python-2-7-is-coming-are-you-ready/]), can we simply remove it from the testing list?

**Comment by empireshades** [comment]
Bumping this as per my previous message (above):

> This seems to fail only on the python 2.7 tests. In light of it being end of life'd (https://www.anaconda.com/end-of-life-eol-for-python-2-7-is-coming-are-you-ready/), can we simply remove it from the testing list?

**Pull request closed without merging**
