### PR TITLE
GitHub Pull Request Template Update

### PR DESCRIPTION
**Pull request by MinchinWeb**
Further to #911, this aims to improve the Pull Request template, by including a reminder of the commands to run locally for test, lints, etc.

### Checklist
- [x] The code change is tested and works locally.
- [ n/a ] Tests pass. Your PR cannot be merged unless tests pass
- [x] There is no commented out code in this PR.
- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ n/a ] Have you written new tests for your core changes, as applicable?

### CODE REVIEW

**Comment by wren** [comment]
@MinchinWeb Thanks for this. 

Out of curiosity, do you have `make` set up on your computer?

**Comment by MinchinWeb** [comment]
No, I don't have `make` installed here (as, I think, is typical of Windows machines). (or `bash` for the matter...)

[invoke](http://www.pyinvoke.org/) might be a good pure-Python alternative that I've used in the past that might do what you want.

**Comment by wren** [comment]
That's great; I was actually hoping you didn't have it. Would you mind going through the contributing doc and getting set up? I'd love your notes on whether there's enough info there or not for the Windows setup.

**Comment by wren** [comment]
Forgot to @MinchinWeb for the above comment.

**Pull request merged**
