### PR TITLE
Close file handle before passing edit's tempfile to editor.

### PR DESCRIPTION
**Pull request by MinchinWeb**
Fix for #415 on Windows.

### CODE REVIEW

**Comment by xemoka** [comment]
Will this ever get merged or is there some conflict for doing it this way?

**Comment by mrlo** [comment]
Also looking to see if this is going to get merged...

**Comment by arisAlexis** [comment]
bump

**Comment by wren** [comment]
This looks like a great fix, and we'd love to merge it. Would you mind resolving the merge conflict?

**Comment by MinchinWeb** [comment]
@wren Will do!

**Comment by MinchinWeb** [comment]
@wren: the pull request has been recreated and passes the test suite. I'm don't think there was a test in place for this particular issue.

**Comment by wren** [comment]
@MinchinWeb It looks like this was maybe already fixed by [another pr](https://github.com/jrnl-org/jrnl/pull/564)? Sorry for the back and forth, but I hadn't seen the other one when I commented here.

Is there some reason the `os.close` call needs to be moved up a few lines like this PR does?

**Comment by MinchinWeb** [comment]
@wren: yes, this is almost identical to #564, except that that one got applied to the 1.9.x branch, but has never been merged into the 2.0 branch; this one applies directly to the 2.0 branch. So this should be applied to the 2.0 branch, or #564 should be cherry-picked to the 2.0 branch.

As for the location of closing the filehandle, first here is the code:

```
    filehandle, tmpfile = tempfile.mkstemp(prefix="jrnl", text=True, suffix=".txt")
    os.close(filehandle)  # in PR 564
    with codecs.open(tmpfile, 'w', "utf-8") as f:
        if template:
            f.write(template)
    os.close(filehandle)  # in PR 416 (this one)
```

Personally, I like it lower, as it maintains the file lock if we decide to write the template file to our temp file.

**Comment by wren** [comment]
@sergiorgiraldo v2.0 is out now, and I believe has a fix for this already. Can you please upgrade from v1.9.8 and confirm the fix?

**Comment by wren** [comment]
Already fixed.

**Comment by wren** [comment]
@sergiorgiraldo Sorry, this wasn't actually fixed, apparently! It looks like @micahellison has submitted the actual fix [here](https://github.com/jrnl-org/jrnl/pull/792).

**Pull request closed without merging**
