### PR TITLE
Add '-not' flag for excluding tags from filter

### PR DESCRIPTION
**Pull request by jprof**
This change adds a new flag to exlude all tags after it. A rough example:

```
-> jrnl @wat --short
2019-07-25 18:16 @todo @wat wat2
2019-07-27 18:25 @todo @wat @not test
2019-07-28 21:54 @todo @wat wat2
-> jrnl @wat -not @not --short
2019-07-25 18:16 @todo @wat wat2
2019-07-28 21:54 @todo @wat wat2
```

### CODE REVIEW

**Comment by wren** [comment]
This is looking good. Can you please add some tests for this? The tests can be the examples that you posted in this PR.

**Comment by jprof** [comment]
> This is looking good. Can you please add some tests for this? The tests can be the examples that you posted in this PR.

Thanks @wren, I actually was not familiar with `behave` so I didn't know there were tests until your comment. Would you be willing to take an update to the CONTRIBUTING file to demonstrate how it is used? I'd be happy to open a new PR if so.

**Comment by wren** [comment]
I think that's a good idea. We have an milestone to update documentation, so we should include this in that.

**Comment by wren** [comment]
@jprof Thank you!

**Pull request merged**
