### PR TITLE
Reading

### LINKED ISSUE #344: Clarify usage output between export and reading sections
When reading the usage output, I didn't expect to be able to use --short while reading a journal, but it worked.  This makes sense knowing the code, but just from reading the usage it is unexpected.

I think '--short' and '--tags' should be listed under 'Reading' with a note under 'Export' that 'Reading''s options can also be used.

<pre>
usage: jrnl [-h] [-v] [-ls] [-from DATE] [-until DATE] [-on DATE] [-and]
            [-starred] [-n [N]] [--short] [--tags] [--export TYPE] [-o OUTPUT]
            [--encrypt [FILENAME]] [--decrypt [FILENAME]] [--edit]
            [[...]]

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         prints version information and exits
  -ls                   displays accessible journals

Composing:
  To write an entry simply write it on the command line, e.g. "jrnl
  yesterday at 1pm: Went to the gym."

  

Reading:
  Specifying either of these parameters will display posts of your journal

  -from DATE            View entries after this date
  -until DATE, -to DATE
                        View entries before this date
  -on DATE              View entries on this date
  -and                  Filter by tags using AND (default: OR)
  -starred              Show only starred entries
  -n [N]                Shows the last n entries matching the filter. '-n 3'
                        and '-3' have the same effect.

Export / Import:
  Options for transmogrifying your journal

  --short               Show only titles or line containing the search tags
  --tags                Returns a list of all tags and number of occurences
  --export TYPE         Export your journal. TYPE can be json, markdown, or
                        text.
  -o OUTPUT             Optionally specifies output file when using --export.
                        If OUTPUT is a directory, exports each entry into an
                        individual file instead.
  --encrypt [FILENAME]  Encrypts your existing journal with a new password
  --decrypt [FILENAME]  Decrypts your journal and stores it in plain text
  --edit                Opens your editor to edit the selected entries.
</pre>

### PR DESCRIPTION
**Pull request by mzfr**
Fixes #344

### CODE REVIEW

**Comment by mzfr** [comment]
@maebert 	oh so now if `short` or `tag` is passed I should be making it a read.

meaning I should change that line to

```python
    elif args.decrypt is not False or args.encrypt is not False or args.export is not False or args.edit:
```

right?

**Comment by maebert** [comment]
Sounds about right, yes!

**Comment by maebert** [comment]
Hm, that doesn't quite line up with expected behaviour yet (see the failing tests)

**Comment by mzfr** [comment]
@wren any reason for closing this?

**Comment by wren** [comment]
@msfr I deleted the rc2 branch, since we already released. I didn't see this PR was for that branch. Sorry!

All PRs should be for the master branch now.

**Comment by wren** [comment]
This was my mistake while organizing the branches. Sorry about that. Can you please reopen both your PRs into the master branch?

**Comment by mzfr** [comment]
okay I'll make both of the PRs to master branch ASAP

**Comment by wren** [comment]
@mzfr Do you still plan to reopen this PR? Sorry, again for the mix up!

**Comment by mzfr** [comment]
Yes I am bit busy right now... Will submit them in few hours

**Comment by wren** [comment]
No rush. Just wanted to check in. Thank you!

**Comment by mzfr** [comment]
@wren just to confirm I need to make pull requests to the master branch right?

**Comment by micahellison** [comment]
I'm looking at the line referenced above regarding guess_mode. Looks like that's causing the tests to fail, and also that the current functionality of `jrnl --short` and `jrnl --tag` is working as expected without the change. I think just reverting that change should be fine, unless there's something I'm missing.

As PRs, yes, please keep making PRs to the master branch.

**Pull request closed without merging**
