### PR TITLE
Fix keyring issue on linux

### LINKED ISSUE #654: Random RuntimeError without keyring
I'm using Ubuntu on WSL. Running any jrnl command using an already encrypted journal file without an available keyring backend will sometimes cause the command to randomly fail. It's about 50/50 for me, I have no idea why it is not consistent. If it works, it will just ask for the password, if it doesn't, the following error appears (using --debug):
```
DEBUG    jrnl.cli     Reading configuration from file /<path>/.jrnl_config
DEBUG    jrnl.util    Configuration file /<path>/.jrnl_config read correctly
DEBUG    jrnl.cli     Using configuration "{'journals': {'default': {'journal': '<path>/journal.txt', 'encrypt': True}}, 'editor': '/bin/nano', 'encrypt': True, 'default_hour': 9, 'default_minute': 0, 'timeformat': '%d.%m.%Y %H:%M', 'tagsymbols': '@', 'highlight': True, 'linewrap': 79}"
DEBUG    jrnl.cli     Using journal "default"
DEBUG    jrnl.cli     Updating configuration with specific jourlnal overrides {'journal': '<path>/journal.txt', 'encrypt': True}
DEBUG    jrnl.cli     Using journal path <path>/journal.txt
Traceback (most recent call last):
  File "<path>/bin/jrnl", line 11, in <module>
    load_entry_point('jrnl==1.9.8', 'console_scripts', 'jrnl')()
  File "<path>/lib/python3.7/site-packages/jrnl/cli.py", line 194, in run
    journal = Journal.Journal(journal_name, **config)
  File "<path>/lib/python3.7/site-packages/jrnl/Journal.py", line 39, in __init__
    self.open()
  File "<path>/lib/python3.7/site-packages/jrnl/Journal.py", line 105, in open
    journal = util.get_password(keychain=self.name, validator=validate_password)
  File "<path>/lib/python3.7/site-packages/jrnl/util.py", line 37, in get_password
    pwd_from_keychain = keychain and get_keychain(keychain)
  File "<path>/lib/python3.7/site-packages/jrnl/util.py", line 56, in get_keychain
    return keyring.get_password('jrnl', journal_name)
  File "<path>/lib/python3.7/site-packages/keyring/core.py", line 55, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "<path>/lib/python3.7/site-packages/keyring/backends/fail.py", line 24, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

### PR DESCRIPTION
**Pull request by maebert**
This fixues issues with Keyring on Ubuntu and other Linux distros (fixes #654 #718  #558 #496 #478 #410 #407):

```
RuntimeError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

This PR adds `keyrings.alt` as a requirement on linux. `secretstorage` might have the better and more complete interface to Gnome's keyring, but depends on `libdbus` to be installed, which we don't have control over.

Also see #699.

I tested this on Ubuntu 18.04 LTS, but can't more testing on different platforms would be nice.

### Checklist

- [X] The code change is tested and works locally.
- [X] Tests pass. Your PR cannot be merged unless tests pass
- [X] There is no commented out code in this PR.
- [X] Have you followed the guidelines in our Contributing document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?

### CODE REVIEW

**Comment by wren** [comment]
> Keyrings in this package may have security risks or other implications. These backends were extracted from the main keyring project to make them available for those who wish to employ them, but are discouraged for general production use. Include this module and use its backends at your own risk.

😬 

Is this really the best option we have to solve this?

**Comment by maebert** [comment]
> Is this really the best option we have to solve this?

Alternatively, we could use [Jeepney](https://pypi.org/project/keyring_jeepney/) on Linux, which uses a pure-python DBus implementation to talk to SecretService. However, there's no promise that it's any more or less secure than the implementation in `keyrings.alt`...

**Comment by pspeter** [comment]
Alternatively, we could tell people in the documentation how to fix it themselves (install libdbus and secretstorage). It's probably better than people relying on insecure storage without even realizing that it's insecure. 

Also, my PR #699 fixes some of the keyring issues you linked already (it shouldn't crash anymore when people select "no" to the keyring storage).

**Comment by wren** [comment]
I think we should avoid using anything that says we shouldn't use it in a production setting. Let's leave this out for now and update the docs to show how to fix manually.

We can also put in a link to the docs page when someone runs into the error, in order to be more helpful.

**Pull request closed without merging**
